name: Sugerir Mejora (Feature Request)
about: Sugiere una idea para este proyecto
title: '[FEAT] '
labels: enhancement
assignees: ''

body:
  - type: textarea
    id: problem
    attributes:
      label: ¿Tu sugerencia está relacionada con un problema?
      description: Una descripción clara y concisa de cuál es el problema. Ej. "Me frustra cuando..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Descripción de la solución
      description: Una descripción clara y concisa de lo que quieres que suceda.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Una descripción clara y concisa de cualquier solución o característica alternativa que hayas considerado.
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Añade cualquier otro contexto o capturas de pantalla sobre la solicitud de la característica aquí.
